AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda_demo

  Sample SAM Template for lambda_demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  helloJava:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java11
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::594125200010:role/service-role/helloJava-role-91eez32s'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /helloJava
            Method: POST